# Generated by Django 5.1.1 on 2024-09-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='testimonials_images')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.AddField(
            model_name='membersmodel',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='membersmodel',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='membersmodel',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
