# Generated by Django 5.1.1 on 2024-09-28 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_carmodel_customermodel_service_servicemodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='car',
        ),
        migrations.DeleteModel(
            name='CustomerModel',
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
        migrations.DeleteModel(
            name='ServiceModel',
        ),
    ]
