# Generated by Django 5.1.1 on 2024-09-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_carmodel_customer_remove_servicemodel_car_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('background_image', models.ImageField(upload_to='banner_images')),
                ('image', models.ImageField(upload_to='banner_images')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.RenameModel(
            old_name='Service',
            new_name='AboutModel',
        ),
        migrations.AlterModelOptions(
            name='aboutmodel',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
