# Generated by Django 5.1.1 on 2024-09-28 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicesmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutmodel',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About as'},
        ),
    ]
